apiVersion: v1
kind: Service
metadata:
  name: ms-products       # <--- ESTE NOMBRE ES CRUCIAL
  namespace: appdemo
spec:
  selector:
    app: ms-products      # Debe coincidir con el label del pod
  ports:
  - port: 80              # El puerto visible para el cluster (Gateway llama aquÃ­)
    targetPort: 8000      # El puerto real de tu contenedor Python