apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: appdemo
spec:
  type: LoadBalancer # Expone IP externa (localhost en k3d), en prod usar el Cluster IP
  selector:
    app: api-gateway
  ports:
  - port: 80     # Puerto al que llamas desde afuera
    targetPort: 8000 # Puerto del contenedor